### ISSUE TITLE
Unknown directive ‘script-src-attr’

### ISSUE THREAD

**Issue by frlorenzo** [venables/koa-helmet#60]
After upgrading to 6.0.0 I started to get the following error: Content Security Policy: Couldn’t process unknown directive ‘script-src-attr’. I reverted back to 5.2.0 and the error message is gone. Here's the other packages in use:

├── @koa/cors@3.1.0
├── koa@2.13.0
├── koa-compress@5.0.1
├── koa-favicon@2.1.0
├── koa-helmet@6.0.0
├── koa-logger@3.2.1
├── koa-sslify@4.0.3
└── koa-static@5.0.0

**Comment by venables** [comment]
Hi @frlorenzo, this appears to be an issue with your browser not supporting `script-src-attr` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-attr). 

It is most likely due to an outdated browser. What browser are you using?

I am closing this for now, but feel free to post here with your browser info and I can re-open as needed.
